### ISSUE TITLE
[ADD] Footer Component | Common to all pages

### ISSUE THREAD

**Issue by Dexters-Hub** [TinkerHub-CEC/tinkerhub-cec-website#13]
## Footer Component | Common to all pages

**Which page you want to work with**: _Common to all pages_
**Specific Component that you want to work with**: _Footer Component_

**Are you able to complete it on your own?**:
- [ ] Check if yes.

**Can you complete it in 4 Days**:
- [ ] Check if yes.

## Take and  Add a Screenshot of the Component from the Figma Design FIle

![Screenshot from 2022-09-14 14-14-52](https://user-images.githubusercontent.com/47777599/190106699-da9b6aa9-b735-45b7-89f1-9fec68d32e2c.png)

## Check yourself with this

- [ ] Have you assigned yourself to this issue
- [ ] Have you looked at the Figma File mentioned in issue #1
- [ ] Have you read the [CONTRIBUTING.md](https://github.com/TinkerHub-CEC/tinkerhub-cec-website/blob/main/CONTRIBUTING.md) file
- [ ] Have your tried to run the project? Was it successfull?

CC: @Dexters-Hub if any doubts?

**Comment by developer-irfan** [comment]
Hey i would like to work on this.

**Comment by Dexters-Hub** [comment]
Hey @developer-irfan 👋🏻 

Do check yourself with [CONTRIBUTING.md](https://github.com/TinkerHub-CEC/tinkerhub-cec-website/blob/main/CONTRIBUTING.md) and all steps, and checks mentioned.

Let me know when you complete it.

Happy Hacking ❤️

**Comment by developer-irfan** [comment]
@Dexters-Hub i am facing this issue while running project by yarn start
![Capture](https://user-images.githubusercontent.com/111001343/190205484-076c98fc-7345-4fc6-9adc-a8ad6ea2ecfe.PNG)

**Comment by Dexters-Hub** [comment]
> @Dexters-Hub i am facing this issue while running project by yarn start ![Capture](https://user-images.githubusercontent.com/111001343/190205484-076c98fc-7345-4fc6-9adc-a8ad6ea2ecfe.PNG)

To work in Development Environment - try to run it using the command 
```
yarn dev
```
