### ISSUE TITLE
[ADD] Connect with us Component | Home Page

### ISSUE THREAD

**Issue by Dexters-Hub** [TinkerHub-CEC/tinkerhub-cec-website#6]
## Connect with us Component | Home Page

**Which page you want to work with**: _Home_
**Specific Component that you want to work with**: _Connect with us Component_
**Are you able to complete it by your own?**: _yes_

## Take and  Add a Screenshot of the Component from the Figma Design FIle

![Screenshot from 2022-09-13 17-35-38](https://user-images.githubusercontent.com/47777599/189897496-831d46b8-28cb-4760-84bb-854b9aa940ae.png)

## Check yourself with this @Abin-T-Sunil 

- [x] Have you assigned yourself with this issue
- [x] Have you looked at the Figma File mentioned in issue #1
- [ ] Have you read the [CONTRIBUTING.md](https://github.com/TinkerHub-CEC/tinkerhub-cec-website/blob/main/CONTRIBUTING.md) file
- [ ] Have your tried to run the project? Was it successful?

CC: @Dexters-Hub

**Comment by developer-irfan** [comment]
Hello @Dexters-Hub assign me this i will create 'connect with us' component in home page

**Comment by Dexters-Hub** [comment]
Hey @developer-irfan 👋🏻 
Thank you for pining me

Unfortunately, this issue has been already assigned.

Keep a 👀 watch for the repository and star ⭐  it. As there will be more issues raised soon and you can work on them. 

Happy Hacking 💖
